// Collects every open [confirm] item into docs/confirm-report.md for Rae (plan §5, Phase 2 acceptance):
// business.json, claims.json, src/content/services/*.json, and every
// <Confirm note="…"> in the source. `--strict` exits 1 while anything is open (use before launch).
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';

const json = (p) => JSON.parse(readFileSync(p, 'utf8'));
const business = json('src/data/business.json');
const claims = json('src/data/claims.json');
const SERVICES_DIR = 'src/content/services';
const services = readdirSync(SERVICES_DIR)
  .filter((f) => f.endsWith('.json'))
  .map((f) => ({ id: f.replace(/\.json$/, ''), ...json(join(SERVICES_DIR, f)) }))
  .sort((a, b) => a.order - b.order);
const serviceItems = services.flatMap((s) => [
  ...(s.confirmed ? [] : [`**${s.name}**: offer this service? (hidden in production until confirmed)`]),
  ...s.confirm.map((c) => `**${s.name}**: ${c}`),
  ...(s.faq ?? []).filter((f) => f.confirm).map((f) => `**${s.name}**, FAQ "${f.q}": ${f.confirm}`),
]);

// <Confirm note="…" /> and <Confirm note={'…'} /> in components and pages, with the file they're in.
// Consignment (VOW Phase 4): [confirm] items, and the lawyer-gated unit types in their own section.
const consign = json('src/data/consign.json');
const consignItems = [
  ...consign.types.filter((t) => !t.confirmed).map((t) => `**${t.label}**: offer consignment of this type?`),
  ...consign.types.flatMap((t) => t.confirm.map((c) => `**${t.label}**: ${c}`)),
  ...[...consign.steps, ...consign.terms].filter((x) => x.confirm).map((x) => `**${x.label ?? x.title}**: ${x.confirm}`),
  ...consign.faq.filter((f) => f.confirm).map((f) => `FAQ "${f.q}": ${f.confirm}`),
];
const lawyerItems = consign.types.filter((t) => t.lawyer).map((t) => `**${t.label}** (consignment): ${consign.lawyerNote}`);

const notes = new Map();
const lawyerNotes = new Map(); // <Confirm lawyer note="…">
const walk = (dir) => {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) { walk(p); continue; }
    if (!/\.(astro|tsx)$/.test(p)) continue;
    for (const m of readFileSync(p, 'utf8').matchAll(/<Confirm( lawyer)? note=(?:"([^"]+)"|\{['"]([^'"]+)['"]\})/g)) {
      const map = m[1] ? lawyerNotes : notes;
      const note = m[2] ?? m[3];
      if (!map.has(note)) map.set(note, new Set());
      map.get(note).add(p.replaceAll('\\', '/').replace(/^src\//, ''));
    }
  }
};
walk('src');

const lines = [
  '# Open [confirm] items',
  '',
  `Generated by \`npm run confirm-report\` on ${new Date().toISOString().slice(0, 10)}. Everything here is shown on the review build with a yellow [confirm] chip and needs an answer from Rae (or Paul) before launch.`,
  '',
  '## Business details (`src/data/business.json`)',
  ...business.confirm.map((c) => `- [ ] ${c}`),
  '',
  '## Claims from the old site (`src/data/claims.json`, hidden in production until confirmed)',
  ...claims.items.filter((c) => !c.confirmed).map((c) => `- [ ] ${c.text}`),
  '',
  '## For the lawyer (`src/data/consign.json` types with `lawyer: true`, plus `<Confirm lawyer>` flags below)',
  ...lawyerItems.map((c) => `- [ ] ${c}`),
  ...[...lawyerNotes].sort().map(([note, files]) => `- [ ] ${note} (${[...files].join(', ')})`),
  '',
  '## Consignment (`src/data/consign.json`)',
  ...consignItems.map((c) => `- [ ] ${c}`),
  '',
  '## Services (`src/content/services/`)',
  ...serviceItems.map((c) => `- [ ] ${c}`),
  '',
  '## Flags in page copy',
  '',
];
for (const [note, files] of [...notes].sort()) lines.push(`- [ ] ${note} (${[...files].join(', ')})`);
lines.push('');

const total = business.confirm.length + claims.items.filter((c) => !c.confirmed).length + serviceItems.length
  + consignItems.length + lawyerItems.length + lawyerNotes.size + notes.size;
writeFileSync('docs/confirm-report.md', lines.join('\n'));
console.log(`docs/confirm-report.md: ${total} open item(s)`);
if (process.argv.includes('--strict') && total > 0) process.exit(1);
