// Collects every open [confirm] item into docs/confirm-report.md for Rae (plan §5, Phase 2 acceptance):
// business.json, claims.json (and services once they exist), and every
// <Confirm note="…"> in the source. `--strict` exits 1 while anything is open (use before launch).
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';

const json = (p) => JSON.parse(readFileSync(p, 'utf8'));
const business = json('src/data/business.json');
const claims = json('src/data/claims.json');

// <Confirm note="…" /> and <Confirm note={'…'} /> in components and pages, with the file they're in.
const notes = new Map();
const walk = (dir) => {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) { walk(p); continue; }
    if (!/\.(astro|tsx)$/.test(p)) continue;
    for (const m of readFileSync(p, 'utf8').matchAll(/<Confirm note=(?:"([^"]+)"|\{['"]([^'"]+)['"]\})/g)) {
      const note = m[1] ?? m[2];
      if (!notes.has(note)) notes.set(note, new Set());
      notes.get(note).add(p.replaceAll('\\', '/').replace(/^src\//, ''));
    }
  }
};
walk('src');

const lines = [
  '# Open [confirm] items',
  '',
  `Generated by \`npm run confirm-report\` on ${new Date().toISOString().slice(0, 10)}. Everything here is shown on the review build with a yellow [confirm] chip and needs an answer from Rae (or Paul) before launch.`,
  '',
  '## Business details (`src/data/business.json`)',
  ...business.confirm.map((c) => `- [ ] ${c}`),
  '',
  '## Claims from the old site (`src/data/claims.json`, hidden in production until confirmed)',
  ...claims.items.filter((c) => !c.confirmed).map((c) => `- [ ] ${c.text}`),
  '',
  '## Flags in page copy',
  '',
];
for (const [note, files] of [...notes].sort()) lines.push(`- [ ] ${note} (${[...files].join(', ')})`);
lines.push('');

const total = business.confirm.length + claims.items.filter((c) => !c.confirmed).length + notes.size;
writeFileSync('docs/confirm-report.md', lines.join('\n'));
console.log(`docs/confirm-report.md: ${total} open item(s)`);
if (process.argv.includes('--strict') && total > 0) process.exit(1);
